'use client';

import React from 'react';
import { ValueOrigin } from '@/types';
import { designTokens } from '@/lib/design-tokens';

interface ValueOriginChipProps {
  origin: ValueOrigin;
  className?: string;
  showTooltip?: boolean;
}

export function ValueOriginChip({ origin, className = '', showTooltip = true }: ValueOriginChipProps) {
  const token = designTokens.origins[origin] || designTokens.origins.DERIVED;

  const tooltipText: Record<ValueOrigin, string> = {
    USER_PROVIDED: 'Input provided directly by the assessment creator.',
    CALCULATED: 'Authoritative deterministic financial fact calculated by backend.',
    DERIVED: 'Mathematical derivation combining multiple validated metrics.',
    ESTIMATED: 'Based on benchmark ratios or standard industry assumptions.',
    CATALOG: 'Standard published SAP BTP list pricing.',
    AI_INTERPRETED: 'Advisory analysis generated by ValueLens AI Intelligence Engine.'
  };

  return (
    <span
      title={showTooltip ? tooltipText[origin] : undefined}
      className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium border ${token.bg} ${token.text} ${token.border} ${className}`}
    >
      <span className="w-1.5 h-1.5 rounded-full mr-1.5 bg-current opacity-70" />
      {token.label}
    </span>
  );
}
